export const DASHBOARD_ACTION_TYPES = {
    ADD_LIST_ITEM: 'ADD_LIST_ITEM',
    DELETE_LIST_ITEM: 'DELETE_LIST_ITEM',
    ADD_CARD_ITEM: 'ADD_CARD_ITEM',
    DELETE_CARD_ITEM: 'DELETE_CARD_ITEM',
    SET_DND_SORCE: 'SET_DND_SOURCE',
    SET_DND_TARGET: 'SET_DND_TARGET',
    PERFORM_DND: 'PERFORM_DND'
};